spring:
   datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: sa
   password: '{cipher}AQB3ghOq3OysznHjoAd5Nk1EEZdo7WXkj+gHR/NlACtWNirosZ7pGSpeTxDuBTH8lO5JhhnNce4lxrAM/S88NuIt6PrR3wLsIfmoSop4kueC/2vcby8DwMtRM+FtQu0GnBd53kwvWaCMBawhMzgCqKgrHIhu2cin3s8fbT/Roc2vo2P1Yx1GuPdpx9sZxlVHSuOLt5htpb93TSjo8uCko6UG3WSeIyFHL1ZzrWRgH0wnZ7OnveKdxJoiLQKs2uNYfhnZOuIF+ToQJbIip3t/09kd6ddQHR9PB5VWLSV4YGM13vOethODdu4coiGFFY78czei9ju24rniT65YejHKrPKUlPYTR+iL8HxSAh9GCmNCOUHEekqr1cUgzlB21HfRgfg='
token:
  expiration_time: 864000000
  secret: user_token_native_user_service_default

gateway:
  ip: 168.154.231.121