spring:
   datasource:
   driver-class-name: org.h2.Driver
   url: jdbc:h2:mem:testdb
   username: sa
   password: '{cipher}AQAmSorbnVjfRQub2wTJpW7baM+D2iJCh8cY9zvpww5x09AAu7yWxygh98q8BCvIV3K3fQh/T45F7+cNpAfZdvBLNQ4WM1m9+QBIzhAIFZVRwm9nYPtkgYAHbSS8p5HxI8LduKc5oJj/KtIhwul6nL1qkryTue5mBjYOAFL4TmRRpzB6iL0UuvMIPsULhLk1jumSFZqRuLIyy3qS6BIr//RoZynMbxJ/mMax2+iCMa5pvo30yBIXsWho4HmT78/Sm9SItnf1YHs03CJE6M30tLyGTt68DTRaev1PJXyU0TdXncfarUkHxi5uFjCW8QuucG48stoUX38GQ1acjTEMGN4KDdpiHiLrdNloktxDcUZuaMbu3tskY1WK1A8rzJ7gNNc='
token:
  expiration_time: 864000000
  secret: user_token_native_user_service_default

gateway:
  ip: 168.154.231.121

order_service:
  url: http://127.0.0.1:8888/order-service/%s/orders